language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
  - "16"

install:
  - export CXX="g++-4.8" CXX="gcc-4.8"
  - npm install -g istanbul
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

after_script: make test-coveralls

sudo: false
