import TAGByte from './tags/byte.d';
import TAGShort from './tags/short.d';
import TAGInt from './tags/int.d';
import TAGLong from './tags/long.d';
import TAGFloat from './tags/float.d';
import TAGDouble from './tags/double.d';
import TAGByteArray from './tags/byte_array.d';
import TAGString from './tags/string.d';
import TAGList from './tags/list.d';
import TAGCompound from './tags/compound.d';
import TAGIntArray from './tags/int_array.d';

declare const _exports: {
  TAGByte: typeof TAGByte;
  TAGShort: typeof TAGShort;
  TAGInt: typeof TAGInt;
  TAGLong: typeof TAGLong;
  TAGFloat: typeof TAGFloat;
  TAGDouble: typeof TAGDouble;
  TAGByteArray: typeof TAGByteArray;
  TAGString: typeof TAGString;
  TAGList: typeof TAGList;
  TAGCompound: typeof TAGCompound;
  TAGIntArray: typeof TAGIntArray;
  1: typeof TAGByte;
  2: typeof TAGShort;
  3: typeof TAGInt;
  4: typeof TAGLong;
  5: typeof TAGFloat;
  6: typeof TAGDouble;
  7: typeof TAGByteArray;
  8: typeof TAGString;
  9: typeof TAGList;
  10: typeof TAGCompound;
  11: typeof TAGIntArray;
  TAG_Byte: number;
  TAG_Short: number;
  TAG_Int: number;
  TAG_Long: number;
  TAG_Float: number;
  TAG_Double: number;
  TAG_Byte_Array: number;
  TAG_String: number;
  TAG_List: number;
  TAG_Compound: number;
  TAG_Int_Array: number;
};

export = _exports;
